### ISSUE TITLE
again split method

### ISSUE THREAD

**Issue by hvasbath** [emolch/pyrocko#104]
I get assertion error when using the replaced_crust method:
The number below are just printed out depth min and depth max.
None 32000.0
18000.0 None

So basically it doesnt know how to handle None' s yet. I am also not sure if the conditions below work correctly then...

@HerrMuellerluedenscheid could you please have a look into that?
Thanks a lot!

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)

    715     source_model = cake.load_model(earth_model,
--> 716                                    crust2_profile=source_profile).extract(
    717                                    depth_max=source_depth_max * km)
    718 

/usr/local/lib/python2.7/dist-packages/pyrocko/cake.pyc in load_model(fn, format, crust2_profile)
   3430     mod = LayeredModel.from_scanlines(reader)
   3431     if crust2_profile is not None:
-> 3432         return mod.replaced_crust(crust2_profile)
   3433 
   3434     return mod

/usr/local/lib/python2.7/dist-packages/pyrocko/cake.pyc in replaced_crust(self, crust2_profile, crustmod)
   3233                 moho1 = element
   3234 
-> 3235         mod = self.extract(depth_min='moho')
   3236         first = True
   3237         for element in mod.elements():

/usr/local/lib/python2.7/dist-packages/pyrocko/cake.pyc in extract(self, depth_min, depth_max)
   3187 
   3188         print depth_min, depth_max
-> 3189         assert depth_min<depth_max
   3190 
   3191         mod_extracted = LayeredModel()

AssertionError:

**Comment by HerrMuellerluedenscheid** [comment]
Fix a0f9be515b8e29e9f8bf98a38e8e01cc813a45a5
