### ISSUE TITLE
too many open stores

### ISSUE THREAD

**Issue by hvasbath** [emolch/pyrocko#111]
834     response = engine.process(sources=sources,
--> 835                               targets=targets, nprocs=nprocs)
    836 
    837     synt_trcs = []

/usr/local/lib/python2.7/dist-packages/pyrocko/gf/seismosizer.pyc in process(self, *args, **kwargs)
   2628         store_ids = set(target.store_id for target in request.targets)
   2629         for store_id in store_ids:
-> 2630             self.get_store(store_id)
   2631 
   2632         m = request.subrequest_map()

/usr/local/lib/python2.7/dist-packages/pyrocko/gf/seismosizer.pyc in get_store(self, store_id)
   2475         if store_id not in self._open_stores:
   2476             store_dir = self.get_store_dir(store_id)
-> 2477             self._open_stores[store_id] = store.Store(store_dir)
   2478 
   2479         return self._open_stores[store_id]

/usr/local/lib/python2.7/dist-packages/pyrocko/gf/store.pyc in __init__(self, store_dir, mode, use_memmap)
   1098                 '("config" file not found)' % store_dir)
   1099 
-> 1100         self.config = meta.load(filename=config_fn)
   1101         self._decimated = {}
   1102         self._extra = {}

/usr/local/lib/python2.7/dist-packages/pyrocko/guts.pyc in g(*args, **kwargs)
     70 
     71             elif filename is not None:
---> 72                 stream = open(filename, mode)
     73                 kwargs['stream'] = stream
     74                 retval = f(*args, **kwargs)

IOError: [Errno 24] Too many open files: '/data3TB/Teleseism/Greensfunctions/Aqaba1995GFS/TIXI_ak135_1.000Hz_19/config'

I have a step where I calculate all the covariances between the velocity models which is for 
28 stations times 21 velocity models = 588 stores

After like 15 stations ergo sth like 300 stores opened this error shows up...

**Comment by HerrMuellerluedenscheid** [comment]
One solution for now might be to change the maximum number of allowed open files. Maybe this helps? 

http://stackoverflow.com/questions/6774724/why-python-has-limit-for-count-of-file-handles

the better solution would be to read exactly that number an allow the  _open_stores

**Comment by HerrMuellerluedenscheid** [comment]
(Finger hit the send button by accident) to check the length of _open_stores when opening a new one. If too many stores are open (maybe) the first one which has been opened could be closed instead. I'm not sure about effects regarding performance, overhead, etc. but maybe this be worth a try. just a guessing from the tram, though.

**Comment by hvasbath** [comment]
Yes I did it this way. Wrote an close_cashed_stores function ...
https://github.com/hvasbath/pyrocko/pull/1

However it is again a mess. I cannot create a PR here- because it includes all the other changes ...

**Comment by miili** [comment]
Resolved in b7318e6
