### ISSUE TITLE
fomosto build with qseis6a parsing error norm factor

### ISSUE THREAD

**Issue by miili** [emolch/pyrocko#48]
Hi,

I tried building a GF database using `fomosto` with [qseis6a](http://ftp.gfz-potsdam.de/pub/home/turk/wang/qseis2006a-code+input.rar)(http -> ftp) today. Unfortunately it failed due to parsing error of the /tmp/qseis-<uid>/input.

It failed parsing

```
#        FILTER PARAMETERS OF RECEIVERS (SEISMOMETERS OR HYDROPHONES)^M
#        ============================================================^M
# 1. constant factor (in complex format)^M
```

Looking into the qseis6a example input file it turned out that the constant factor (l. 142) has to be complex, fomosto however delivers a float. Which results in a parsing error of qseis.

cheers,

Marius

**Comment by emolch** [comment]
You must use the qseis package from http://kinherd.org/qseis-1.2.tar.gz, because it contains some fixes with too long lines in the input. Very likely the problem is related to that.

**Comment by emolch** [comment]
Aah... just talked with Rongjiang. There are two versions of qseis: qseis6 and qseis6a. I have been using qseis6 until now and there the constant is real, not complex. qseis6a contains some modifications over qseis6 which make it more accurate for small omega, and static displacements. So I should upgrade to the newer version. Have to figure out how to do that without breaking current working setups of fomosto users...

**Comment by miili** [comment]
Great!

FYI, this was the only modification to get qseis6a running with fomosto.

**Comment by emolch** [comment]
Since aaa39e7372731eb1aac74f741e2025b66bf60481, we can now switch between qseis.6 and qseis.6a.

Use `fomosto init qseis.6a <store-id>` to create a qseis version 6a store. Qseis should be runnable as `qseis6a` in this case.

**Comment by eigenblutwurst** [comment]
As you renamed how the binaries for qseis are being called - shall I just rename my qseis bin now to fomosto_qseis2006? Or do I have to recompile qseis in a special way?

**Comment by emolch** [comment]
Please use one of these Packages:

* `qseis_2006a`: http://kinherd.org/fomosto-qseis-2006a.tar.gz
* `qseis_2006`: http://kinherd.org/fomosto-qseis-2006.tar.gz

The 'a' version contains some improvements by Rongjiang.
