### ISSUE TITLE
fomosto workers, parallel processing

### ISSUE THREAD

**Issue by eigenblutwurst** [emolch/pyrocko#57]
I am using Ubuntu 12.04. on an 8 core dell workstation.
I started fomosto with 8 workers in order to make use of the 8 cores. (build(storedir, nworkers=8))
When I check the usage of processors with the linux "top" command however, I see that the 8 jobs of qseis run on just one processor. How may I allocate them to the different processors? Is this a problem in my operation system?
Thank you for your answer!

**Comment by HerrMuellerluedenscheid** [comment]
Hi, 

Unfortunately, I cannot answer that question right away. Still, I might be able to give a hint. I just ran fomosto build in a virtual machine using a version of ubuntu 12.04 64 bit and it finished as expected and ran on both available cpus as expected.
Thus, it does not seem to be a problem of ubuntu 12.04.

**Comment by eigenblutwurst** [comment]
That problem is resolved. Just the top command is not very well suited to evaluate the usage of the CPUs. I can recommend gnome-system-monitor. So fomosto works well and all the CPUs are being used!
