### ISSUE TITLE
fomosto time window

### ISSUE THREAD

**Issue by eigenblutwurst** [emolch/pyrocko#59]
While executing fomosto with 
fomosto build --nworkers=6 --force
I get an error message for module gf script store.py line 1302
determination of time window failed

What could have gone wrong here?
I executed the same scripts for other stations with different distance before and it was working all well.

Thank you for your help!

This is the config in file:
--- !pf.ConfigTypeA
id: crust2_KMBO
modelling_code_id: qseis
earthmodel_1d: |2
      0.             2.5            1.2            2.1           50.            50.
      1.             2.5            1.2            2.1           50.            50.
      1.             6.             3.4            2.7          600.           400.
     11.             6.             3.4            2.7          600.           400.
     11.             6.6            3.7            2.9         1432.           600.
     22.             6.6            3.7            2.9         1432.           600.
     22.             7.2            4.             3.1         1458.           600.
     32.             7.2            4.             3.1         1458.           600.
  mantle
     32.             8.037          4.485          3.607        962.9          399.8
     80.             8.04           4.481          3.5         1008.           417.6
     80.             8.045          4.49           3.502        182.            75.6
    120.             8.05           4.5            3.427        182.6           76.06
    120.             8.05           4.5            3.427        182.6           76.06
    165.             8.175          4.509          3.371        188.7           76.55
    210.             8.301          4.518          3.324        201.            79.4
    210.             8.3            4.519          3.323        338.2          133.7
    300.             8.628          4.679          3.401        353.6          138.7
    410.             9.03           4.87           3.506        377.5          146.5
    410.             9.36           5.08           3.929        414.1          162.7
    660.            10.2            5.611          3.918        428.5          172.9
    660.            10.79           5.965          4.24        1349.           549.5
earthmodel_receiver_1d: |2
      0.             2.5            1.2            2.1           50.            50.
      0.25           2.5            1.2            2.1           50.            50.
      0.25           6.             3.5            2.7          600.           400.
     12.25           6.             3.5            2.7          600.           400.
     12.25           6.6            3.7            2.9         1432.           600.
     24.25           6.6            3.7            2.9         1432.           600.
     24.25           7.2            4.             3.1         1458.           600.
     38.             7.2            4.             3.1         1458.           600.
  mantle
     38.             8.037          4.484          3.593        968.5          402.
     80.             8.04           4.481          3.5         1008.           417.6
     80.             8.045          4.49           3.502        182.            75.6
    120.             8.05           4.5            3.427        182.6           76.06
    120.             8.05           4.5            3.427        182.6           76.06
sample_rate: 2.0
ncomponents: 10
component_scheme: elastic10
tabulated_phases:
- !pf.TPDef
  id: any_P
  definition: p,P,p\,P\
- !pf.TPDef
  id: any_S
  definition: s,S,s\,S\
- !pf.TPDef
  id: slowest
  definition: '0.8'
receiver_depth: 0.0
source_depth_min: 1000.0
source_depth_max: 30000.0
source_depth_delta: 1000.0
distance_min: 3152395.003627918
distance_max: 3552395.003627918
distance_delta: 1000.0

**Comment by HerrMuellerluedenscheid** [comment]
Hi eigenblutwurst,

Does the job start at all or is the exception thrown immediately? I just tested you config file and it seems to be working
```
marius@taurus:~/crust2_KMBO$ fomosto build --nworkers=6 --force
fomosto:fomosto.qseis        - INFO     - Starting block 1 / 150
.... etc.
```
I am not sure if the error you mentioned above can possibly be traced back to a formatting problem of the config file. When pasting code use the capabilities of markdown and prepend and append three dashes (```) so that the syntax is preserved. 

So, the config file I used worked fine:
```
--- !pf.ConfigTypeA 
id: crust2_KMBO
modelling_code_id: qseis
earthmodel_1d: |2
    0. 2.5 1.2 2.1 50. 50.
    1. 2.5 1.2 2.1 50. 50.
    1. 6. 3.4 2.7 600. 400.
    11. 6. 3.4 2.7 600. 400.
    11. 6.6 3.7 2.9 1432. 600.
    22. 6.6 3.7 2.9 1432. 600.
    22. 7.2 4. 3.1 1458. 600.
    32. 7.2 4. 3.1 1458. 600.
   mantle
    32. 8.037 4.485 3.607 962.9 399.8
    80. 8.04 4.481 3.5 1008. 417.6
    80. 8.045 4.49 3.502 182. 75.6
    120. 8.05 4.5 3.427 182.6 76.06
    120. 8.05 4.5 3.427 182.6 76.06
    165. 8.175 4.509 3.371 188.7 76.55
    210. 8.301 4.518 3.324 201. 79.4
    210. 8.3 4.519 3.323 338.2 133.7
    300. 8.628 4.679 3.401 353.6 138.7
    410. 9.03 4.87 3.506 377.5 146.5
    410. 9.36 5.08 3.929 414.1 162.7
    660. 10.2 5.611 3.918 428.5 172.9
    660. 10.79 5.965 4.24 1349. 549.5
earthmodel_receiver_1d: |2
    0. 2.5 1.2 2.1 50. 50.
    0.25 2.5 1.2 2.1 50. 50.
    0.25 6. 3.5 2.7 600. 400.
    12.25 6. 3.5 2.7 600. 400.
    12.25 6.6 3.7 2.9 1432. 600.
    24.25 6.6 3.7 2.9 1432. 600.
    24.25 7.2 4. 3.1 1458. 600.
    38. 7.2 4. 3.1 1458. 600.
    mantle
    38. 8.037 4.484 3.593 968.5 402.
    80. 8.04 4.481 3.5 1008. 417.6
    80. 8.045 4.49 3.502 182. 75.6
    120. 8.05 4.5 3.427 182.6 76.06
    120. 8.05 4.5 3.427 182.6 76.06
sample_rate: 2.0
ncomponents: 10
component_scheme: elastic10
tabulated_phases:
- !pf.TPDef
    id: any_P
    definition: p,P,p\,P\
- !pf.TPDef
    id: any_S
    definition: s,S,s\,S\
- !pf.TPDef
    id: slowest
    definition: '0.8'
receiver_depth: 0.0
source_depth_min: 1000.0
source_depth_max: 30000.0
source_depth_delta: 1000.0
distance_min: 3152395.003627918
distance_max: 3552395.003627918
distance_delta: 1000.0
```

**Comment by eigenblutwurst** [comment]
Hello Marius,
thank you for your comment. That is really strange that it works for you. I found out compared to the other stations GFs I run that it always failed, because the travel time table calculation produces nothing.

vasyurhm@kw12546:/data3TB/Teleseism/Greensfunctions/Aqaba1995GFS/crust2_KMBO$ fomosto ttt
fomosto:pyrocko.gf.store     - INFO     - making travel time table for phasegroup "any_P"
fomosto:pyrocko.spit         - INFO     - at level  0:  100.0% covered,      1 cell
fomosto:pyrocko.gf.store     - INFO     - making travel time table for phasegroup "any_S"
fomosto:pyrocko.spit         - INFO     - at level  0:  100.0% covered,      1 cell
fomosto:pyrocko.gf.store     - INFO     - making travel time table for phasegroup "slowest"
fomosto:pyrocko.spit         - INFO     - at level  0:  100.0% covered,      1 cell

Could this be because of a strange configuration in the qseis timing below? I thought this includes all the P and S wave arrivals and includes even 30 seconds before the first and 50 after the last. Did I get something wrong? Thanks again for your help!

--- !pf.QSeisConfig
time_region: [any_P-30, last(slowest|any_S)+50]
cut: [any_P-30, last(slowest|any_S)+50]
fade: [any_P-30, any_P-10, last(slowest|any_S)+30, last(slowest|any_S)+50]
relevel_with_fade_in: true
sw_algorithm: 0
slowness_window: [0.0, 0.0, 0.0, 0.0]
wavenumber_sampling: 2.5
aliasing_suppression_factor: 0.1
filter_surface_effects: 0
filter_shallow_paths: 0
filter_shallow_paths_depth: 0.0
sw_flat_earth_transform: 1
gradient_resolution_vp: 0.0
gradient_resolution_vs: 0.0
gradient_resolution_density: 0.0
wavelet_duration_samples: 0.001
wavelet_type: 2

**Comment by eigenblutwurst** [comment]
Apparently the travel time table calculation doesnt work for any stations with distances to event larger than 3200km. Is the 1D model defined there maybe not working well as I defined up there a different structure for source and receiver? But if you get correct ttts?  But I guess the error must be in the input and not in the function right?

**Comment by eigenblutwurst** [comment]
This is one ttt for P phases for a station that worked,
file:///data3TB/Teleseism/Greensfunctions/Aqaba1995GFS/crust2_KIV/ttttest.png

that didnt work although in this distance there should be P arrivals...
file:///data3TB/Teleseism/Greensfunctions/Aqaba1995GFS/crust2_ULN/tttest.png

**Comment by eigenblutwurst** [comment]
This is an example of a station where the ttt calculation worked:

**Comment by eigenblutwurst** [comment]
This is a ttt of a station that worked:
![ttttest](https://cloud.githubusercontent.com/assets/11273616/7369081/40c7071a-edb7-11e4-8335-f53de7d46ea5.png)

This is the failed one (above):
![tttest](https://cloud.githubusercontent.com/assets/11273616/7369107/93884072-edb7-11e4-85ca-0a0a8b7872b7.png)

**Comment by HerrMuellerluedenscheid** [comment]
Ahh!

In the distance range you defined (3152-3552 km) there are none of the phases you defined within any_P and any_S. This is because the model is rather shallow (600km) compared to the lateral extend. That in turn is why you see only bright white when looking at any_P/S ttt. Since in the Qseis config file you define the desired time window according to these two phases you run into trouble. 
So, there are different options. Either you can extend the model, vertically. E.g. you could add  
```   
     764.            11.07           6.215          4.359       1276.           537.1
    849.1           11.21           6.272          4.463       1263.           527.3
   1038.            11.52           6.407          4.616       1230.           506.9
   1227.            11.81           6.527          4.71        1198.           488.
   1416.            12.08           6.636          4.812       1168.           470.4
   1605.            12.33           6.735          4.909       1141.           454.4
```
at the bottom of you model. This will increase the computation time of qseis.
Or you can add a phase to any_P and any_S that arrives within the given boundaries:
```
- !pf.TPDef
    id: any_P
    definition: p,P,p\,P\,Pv_660p
```
That last phase is the upperside reflection at the 660km interface. 
Give it a try!

Best wishes 

Marius

**Comment by eigenblutwurst** [comment]
Ah I am such an idiot! Thanks a lot! That happens if one does not fully understand the concept of these Greensfunction calculations. Now I am a step closer in understanding. Thanks a lot! Everything is working now!
