### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by HerrMuellerluedenscheid** [emolch/pyrocko#78]
ran installation on masterdes with local prefix. See error stack below. Second call of install.py skipped this error

[...]
/bin/sh ./libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.     -fPIC -MT resp_fctns.lo -MD -MP -MF .deps/resp_fctns.Tpo -c -o resp_fctns.lo resp_fctns.c
 gcc -DHAVE_CONFIG_H -I. -fPIC -MT resp_fctns.lo -MD -MP -MF .deps/resp_fctns.Tpo -c resp_fctns.c -o resp_fctns.o
mv -f .deps/resp_fctns.Tpo .deps/resp_fctns.Plo
/bin/sh ./libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.     -fPIC -MT file_ops.lo -MD -MP -MF .deps/file_ops.Tpo -c -o file_ops.lo file_ops.c
 gcc -DHAVE_CONFIG_H -I. -fPIC -MT file_ops.lo -MD -MP -MF .deps/file_ops.Tpo -c file_ops.c -o file_ops.o
mv -f .deps/file_ops.Tpo .deps/file_ops.Plo
/bin/sh ./libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.     -fPIC -MT evresp.lo -MD -MP -MF .deps/evresp.Tpo -c -o evresp.lo evresp.c
 gcc -DHAVE_CONFIG_H -I. -fPIC -MT evresp.lo -MD -MP -MF .deps/evresp.Tpo -c evresp.c -o evresp.o
mv -f .deps/evresp.Tpo .deps/evresp.Plo
/bin/sh ./libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.     -fPIC -MT alloc_fctns.lo -MD -MP -MF .deps/alloc_fctns.Tpo -c -o alloc_fctns.lo alloc_fctns.c
 gcc -DHAVE_CONFIG_H -I. -fPIC -MT alloc_fctns.lo -MD -MP -MF .deps/alloc_fctns.Tpo -c alloc_fctns.c -o alloc_fctns.o
mv -f .deps/alloc_fctns.Tpo .deps/alloc_fctns.Plo
/bin/sh ./libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.     -fPIC -MT parse_fctns.lo -MD -MP -MF .deps/parse_fctns.Tpo -c -o parse_fctns.lo parse_fctns.c
 gcc -DHAVE_CONFIG_H -I. -fPIC -MT parse_fctns.lo -MD -MP -MF .deps/parse_fctns.Tpo -c parse_fctns.c -o parse_fctns.o
mv -f .deps/parse_fctns.Tpo .deps/parse_fctns.Plo
/bin/sh ./libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.     -fPIC -MT print_fctns.lo -MD -MP -MF .deps/print_fctns.Tpo -c -o print_fctns.lo print_fctns.c
 gcc -DHAVE_CONFIG_H -I. -fPIC -MT print_fctns.lo -MD -MP -MF .deps/print_fctns.Tpo -c print_fctns.c -o print_fctns.o
mv -f .deps/print_fctns.Tpo .deps/print_fctns.Plo
/bin/sh ./libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.     -fPIC -MT string_fctns.lo -MD -MP -MF .deps/string_fctns.Tpo -c -o string_fctns.lo string_fctns.c
 gcc -DHAVE_CONFIG_H -I. -fPIC -MT string_fctns.lo -MD -MP -MF .deps/string_fctns.Tpo -c string_fctns.c -o string_fctns.o
mv -f .deps/string_fctns.Tpo .deps/string_fctns.Plo
/bin/sh ./libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.     -fPIC -MT error_fctns.lo -MD -MP -MF .deps/error_fctns.Tpo -c -o error_fctns.lo error_fctns.c
 gcc -DHAVE_CONFIG_H -I. -fPIC -MT error_fctns.lo -MD -MP -MF .deps/error_fctns.Tpo -c error_fctns.c -o error_fctns.o
mv -f .deps/error_fctns.Tpo .deps/error_fctns.Plo
/bin/sh ./libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.     -fPIC -MT evr_spline.lo -MD -MP -MF .deps/evr_spline.Tpo -c -o evr_spline.lo evr_spline.c
 gcc -DHAVE_CONFIG_H -I. -fPIC -MT evr_spline.lo -MD -MP -MF .deps/evr_spline.Tpo -c evr_spline.c -o evr_spline.o
mv -f .deps/evr_spline.Tpo .deps/evr_spline.Plo
/bin/sh ./libtool --tag=CC   --mode=link gcc  -fPIC   -o libevresp.la -rpath /home/des/marius/src/pyrocko/evalresp-3.3.0/lib regexp.lo regerror.lo regsub.lo calc_fctns.lo resp_fctns.lo file_ops.lo evresp.lo alloc_fctns.lo parse_fctns.lo print_fctns.lo string_fctns.lo error_fctns.lo evr_spline.lo  -lm 
mkdir .libs
ar cru .libs/libevresp.a  regexp.o regerror.o regsub.o calc_fctns.o resp_fctns.o file_ops.o evresp.o alloc_fctns.o parse_fctns.o print_fctns.o string_fctns.o error_fctns.o evr_spline.o
ranlib .libs/libevresp.a
creating libevresp.la
(cd .libs && rm -f libevresp.la && ln -s ../libevresp.la libevresp.la)
gcc -DHAVE_CONFIG_H -I.     -fPIC -MT evalresp.o -MD -MP -MF .deps/evalresp.Tpo -c -o evalresp.o evalresp.c
mv -f .deps/evalresp.Tpo .deps/evalresp.Po
/bin/sh ./libtool --tag=CC   --mode=link gcc  -fPIC   -o evalresp evalresp.o -L. -levresp  -lm -lm 
gcc -fPIC -o evalresp evalresp.o  -L/home/des/marius/src/pyrocko/evalresp-3.3.0 /home/des/marius/src/pyrocko/evalresp-3.3.0/.libs/libevresp.a -lm
make[1]: warning:  Clock skew detected.  Your build may be incomplete.
make[1]: Leaving directory `/exthd2/des/marius/src/pyrocko/evalresp-3.3.0'
make: warning:  Clock skew detected.  Your build may be incomplete.
make: Warning: File `.deps/string_fctns.Plo' has modification time 87 s in the future
make[1]: Entering directory `/exthd2/des/marius/src/pyrocko/evalresp-3.3.0'
make[1]: Warning: File `.deps/string_fctns.Plo' has modification time 87 s in the future
test -z "/home/des/marius/src/pyrocko/evalresp-3.3.0/lib" || /bin/mkdir -p "/home/des/marius/src/pyrocko/evalresp-3.3.0/lib"
 /bin/sh ./libtool --mode=install /usr/local/des/ENVI/itt/idl708/bin/install -c  'libevresp.la' '/home/des/marius/src/pyrocko/evalresp-3.3.0/lib/libevresp.la'
/usr/local/des/ENVI/itt/idl708/bin/install -c .libs/libevresp.lai /home/des/marius/src/pyrocko/evalresp-3.3.0/lib/libevresp.la

    The current directory must be set to the ITT directory.
    Change the default to the ITT directory and re-run
    this script.
        
make[1]: *** [install-libLTLIBRARIES] Error 1
make[1]: Leaving directory `/exthd2/des/marius/src/pyrocko/evalresp-3.3.0'
make: *** [install-am] Error 2
error: failed to build the included prerequisites with "sh prerequisites/prerequisites.sh"

**Comment by emolch** [comment]
Hi Marius,

hat bestimmt was mit den komischen systemweiten bashrc Settings zu tun. 
Am besten Du machst es wie ich und setzt in deiner .bashrc gleich am 
Anfang sowas:

export 
PATH='/usr/local/des/matlab/R2011b/bin:/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/X11R6/bin:/usr/games:/usr/lib64/jvm/jre/bin:/usr/lib/mit/bin:/usr/lib/mit/sbin'

export -n LD_LIBRARY_PATH LIBRARY_PATH INCLUDE MANPATH CPATH LPATH NLSPATH


Viel Glück!
Sebastian



Am 26.08.15 um 11:05 schrieb Marius Kriegerowski:

**Comment by HerrMuellerluedenscheid** [comment]
Hi,
Das hat das Problem geloest. Dann mach ich das hier mal wieder zu. Danke!
Gruesse

**Comment by zackspica** [comment]
It has worked for me! Danke!
